// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shrike.proto

package shrike

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UUID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{0}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Simple request message for stubbed service calls..
type StubRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StubRequest) Reset()         { *m = StubRequest{} }
func (m *StubRequest) String() string { return proto.CompactTextString(m) }
func (*StubRequest) ProtoMessage()    {}
func (*StubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{1}
}

func (m *StubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StubRequest.Unmarshal(m, b)
}
func (m *StubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StubRequest.Marshal(b, m, deterministic)
}
func (m *StubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StubRequest.Merge(m, src)
}
func (m *StubRequest) XXX_Size() int {
	return xxx_messageInfo_StubRequest.Size(m)
}
func (m *StubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StubRequest proto.InternalMessageInfo

func (m *StubRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Simple response message for stubbed service calls..
type StubResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StubResponse) Reset()         { *m = StubResponse{} }
func (m *StubResponse) String() string { return proto.CompactTextString(m) }
func (*StubResponse) ProtoMessage()    {}
func (*StubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{2}
}

func (m *StubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StubResponse.Unmarshal(m, b)
}
func (m *StubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StubResponse.Marshal(b, m, deterministic)
}
func (m *StubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StubResponse.Merge(m, src)
}
func (m *StubResponse) XXX_Size() int {
	return xxx_messageInfo_StubResponse.Size(m)
}
func (m *StubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StubResponse proto.InternalMessageInfo

func (m *StubResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// MOVEMENT MESSAGE TYPES
type Movement struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	URI                  string   `protobuf:"bytes,4,opt,name=URI,proto3" json:"URI,omitempty"`
	FeaturedImage        string   `protobuf:"bytes,5,opt,name=featuredImage,proto3" json:"featuredImage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movement) Reset()         { *m = Movement{} }
func (m *Movement) String() string { return proto.CompactTextString(m) }
func (*Movement) ProtoMessage()    {}
func (*Movement) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{3}
}

func (m *Movement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movement.Unmarshal(m, b)
}
func (m *Movement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movement.Marshal(b, m, deterministic)
}
func (m *Movement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movement.Merge(m, src)
}
func (m *Movement) XXX_Size() int {
	return xxx_messageInfo_Movement.Size(m)
}
func (m *Movement) XXX_DiscardUnknown() {
	xxx_messageInfo_Movement.DiscardUnknown(m)
}

var xxx_messageInfo_Movement proto.InternalMessageInfo

func (m *Movement) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Movement) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movement) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Movement) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *Movement) GetFeaturedImage() string {
	if m != nil {
		return m.FeaturedImage
	}
	return ""
}

// Request Message Types
type CreateMovementRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	URI                  string   `protobuf:"bytes,3,opt,name=URI,proto3" json:"URI,omitempty"`
	FeaturedImage        string   `protobuf:"bytes,4,opt,name=featuredImage,proto3" json:"featuredImage,omitempty"`
	User                 string   `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovementRequest) Reset()         { *m = CreateMovementRequest{} }
func (m *CreateMovementRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMovementRequest) ProtoMessage()    {}
func (*CreateMovementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{4}
}

func (m *CreateMovementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovementRequest.Unmarshal(m, b)
}
func (m *CreateMovementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovementRequest.Marshal(b, m, deterministic)
}
func (m *CreateMovementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovementRequest.Merge(m, src)
}
func (m *CreateMovementRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMovementRequest.Size(m)
}
func (m *CreateMovementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovementRequest proto.InternalMessageInfo

func (m *CreateMovementRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateMovementRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateMovementRequest) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *CreateMovementRequest) GetFeaturedImage() string {
	if m != nil {
		return m.FeaturedImage
	}
	return ""
}

func (m *CreateMovementRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type ReadMovementRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMovementRequest) Reset()         { *m = ReadMovementRequest{} }
func (m *ReadMovementRequest) String() string { return proto.CompactTextString(m) }
func (*ReadMovementRequest) ProtoMessage()    {}
func (*ReadMovementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{5}
}

func (m *ReadMovementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMovementRequest.Unmarshal(m, b)
}
func (m *ReadMovementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMovementRequest.Marshal(b, m, deterministic)
}
func (m *ReadMovementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMovementRequest.Merge(m, src)
}
func (m *ReadMovementRequest) XXX_Size() int {
	return xxx_messageInfo_ReadMovementRequest.Size(m)
}
func (m *ReadMovementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMovementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMovementRequest proto.InternalMessageInfo

func (m *ReadMovementRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ListMovementsRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter               string   `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMovementsRequest) Reset()         { *m = ListMovementsRequest{} }
func (m *ListMovementsRequest) String() string { return proto.CompactTextString(m) }
func (*ListMovementsRequest) ProtoMessage()    {}
func (*ListMovementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{6}
}

func (m *ListMovementsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMovementsRequest.Unmarshal(m, b)
}
func (m *ListMovementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMovementsRequest.Marshal(b, m, deterministic)
}
func (m *ListMovementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMovementsRequest.Merge(m, src)
}
func (m *ListMovementsRequest) XXX_Size() int {
	return xxx_messageInfo_ListMovementsRequest.Size(m)
}
func (m *ListMovementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMovementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMovementsRequest proto.InternalMessageInfo

func (m *ListMovementsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListMovementsRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListMovementsRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type UpdateMovementRequest struct {
	Item                 *Movement `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateMovementRequest) Reset()         { *m = UpdateMovementRequest{} }
func (m *UpdateMovementRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMovementRequest) ProtoMessage()    {}
func (*UpdateMovementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{7}
}

func (m *UpdateMovementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMovementRequest.Unmarshal(m, b)
}
func (m *UpdateMovementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMovementRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMovementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMovementRequest.Merge(m, src)
}
func (m *UpdateMovementRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMovementRequest.Size(m)
}
func (m *UpdateMovementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMovementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMovementRequest proto.InternalMessageInfo

func (m *UpdateMovementRequest) GetItem() *Movement {
	if m != nil {
		return m.Item
	}
	return nil
}

type DeleteMovementRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovementRequest) Reset()         { *m = DeleteMovementRequest{} }
func (m *DeleteMovementRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovementRequest) ProtoMessage()    {}
func (*DeleteMovementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{8}
}

func (m *DeleteMovementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovementRequest.Unmarshal(m, b)
}
func (m *DeleteMovementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovementRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovementRequest.Merge(m, src)
}
func (m *DeleteMovementRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovementRequest.Size(m)
}
func (m *DeleteMovementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovementRequest proto.InternalMessageInfo

func (m *DeleteMovementRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// Response Message Types
type CreateMovementResponse struct {
	Item                 *Movement `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateMovementResponse) Reset()         { *m = CreateMovementResponse{} }
func (m *CreateMovementResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMovementResponse) ProtoMessage()    {}
func (*CreateMovementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{9}
}

func (m *CreateMovementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovementResponse.Unmarshal(m, b)
}
func (m *CreateMovementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovementResponse.Marshal(b, m, deterministic)
}
func (m *CreateMovementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovementResponse.Merge(m, src)
}
func (m *CreateMovementResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMovementResponse.Size(m)
}
func (m *CreateMovementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovementResponse proto.InternalMessageInfo

func (m *CreateMovementResponse) GetItem() *Movement {
	if m != nil {
		return m.Item
	}
	return nil
}

type ReadMovementResponse struct {
	Item                 *Movement `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadMovementResponse) Reset()         { *m = ReadMovementResponse{} }
func (m *ReadMovementResponse) String() string { return proto.CompactTextString(m) }
func (*ReadMovementResponse) ProtoMessage()    {}
func (*ReadMovementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{10}
}

func (m *ReadMovementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMovementResponse.Unmarshal(m, b)
}
func (m *ReadMovementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMovementResponse.Marshal(b, m, deterministic)
}
func (m *ReadMovementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMovementResponse.Merge(m, src)
}
func (m *ReadMovementResponse) XXX_Size() int {
	return xxx_messageInfo_ReadMovementResponse.Size(m)
}
func (m *ReadMovementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMovementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMovementResponse proto.InternalMessageInfo

func (m *ReadMovementResponse) GetItem() *Movement {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListMovementsResponse struct {
	Data                 []*Movement `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListMovementsResponse) Reset()         { *m = ListMovementsResponse{} }
func (m *ListMovementsResponse) String() string { return proto.CompactTextString(m) }
func (*ListMovementsResponse) ProtoMessage()    {}
func (*ListMovementsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{11}
}

func (m *ListMovementsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMovementsResponse.Unmarshal(m, b)
}
func (m *ListMovementsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMovementsResponse.Marshal(b, m, deterministic)
}
func (m *ListMovementsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMovementsResponse.Merge(m, src)
}
func (m *ListMovementsResponse) XXX_Size() int {
	return xxx_messageInfo_ListMovementsResponse.Size(m)
}
func (m *ListMovementsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMovementsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMovementsResponse proto.InternalMessageInfo

func (m *ListMovementsResponse) GetData() []*Movement {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateMovementResponse struct {
	Item                 *Movement `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateMovementResponse) Reset()         { *m = UpdateMovementResponse{} }
func (m *UpdateMovementResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMovementResponse) ProtoMessage()    {}
func (*UpdateMovementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{12}
}

func (m *UpdateMovementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMovementResponse.Unmarshal(m, b)
}
func (m *UpdateMovementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMovementResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMovementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMovementResponse.Merge(m, src)
}
func (m *UpdateMovementResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMovementResponse.Size(m)
}
func (m *UpdateMovementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMovementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMovementResponse proto.InternalMessageInfo

func (m *UpdateMovementResponse) GetItem() *Movement {
	if m != nil {
		return m.Item
	}
	return nil
}

type DeleteMovementResponse struct {
	Item                 *Movement `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteMovementResponse) Reset()         { *m = DeleteMovementResponse{} }
func (m *DeleteMovementResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMovementResponse) ProtoMessage()    {}
func (*DeleteMovementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2311c9d8f30f83c3, []int{13}
}

func (m *DeleteMovementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovementResponse.Unmarshal(m, b)
}
func (m *DeleteMovementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovementResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMovementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovementResponse.Merge(m, src)
}
func (m *DeleteMovementResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMovementResponse.Size(m)
}
func (m *DeleteMovementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovementResponse proto.InternalMessageInfo

func (m *DeleteMovementResponse) GetItem() *Movement {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*UUID)(nil), "shrike.UUID")
	proto.RegisterType((*StubRequest)(nil), "shrike.StubRequest")
	proto.RegisterType((*StubResponse)(nil), "shrike.StubResponse")
	proto.RegisterType((*Movement)(nil), "shrike.Movement")
	proto.RegisterType((*CreateMovementRequest)(nil), "shrike.CreateMovementRequest")
	proto.RegisterType((*ReadMovementRequest)(nil), "shrike.ReadMovementRequest")
	proto.RegisterType((*ListMovementsRequest)(nil), "shrike.ListMovementsRequest")
	proto.RegisterType((*UpdateMovementRequest)(nil), "shrike.UpdateMovementRequest")
	proto.RegisterType((*DeleteMovementRequest)(nil), "shrike.DeleteMovementRequest")
	proto.RegisterType((*CreateMovementResponse)(nil), "shrike.CreateMovementResponse")
	proto.RegisterType((*ReadMovementResponse)(nil), "shrike.ReadMovementResponse")
	proto.RegisterType((*ListMovementsResponse)(nil), "shrike.ListMovementsResponse")
	proto.RegisterType((*UpdateMovementResponse)(nil), "shrike.UpdateMovementResponse")
	proto.RegisterType((*DeleteMovementResponse)(nil), "shrike.DeleteMovementResponse")
}

func init() { proto.RegisterFile("shrike.proto", fileDescriptor_2311c9d8f30f83c3) }

var fileDescriptor_2311c9d8f30f83c3 = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x6d, 0x6f, 0x12, 0x41,
	0x10, 0xf6, 0x80, 0x62, 0x3b, 0xb4, 0xb5, 0x2e, 0xd0, 0x5c, 0xb0, 0x35, 0xf5, 0x52, 0x63, 0x3f,
	0x35, 0xa6, 0x7e, 0xf0, 0x25, 0xb6, 0xda, 0x42, 0x62, 0x48, 0xd1, 0x28, 0x04, 0xe3, 0xd7, 0x2b,
	0x37, 0xd0, 0x8d, 0xf7, 0x82, 0xbb, 0x7b, 0x24, 0xfe, 0x05, 0xff, 0x82, 0x3f, 0xd0, 0xbf, 0x61,
	0x76, 0xf7, 0x0e, 0xee, 0xce, 0xa3, 0xf1, 0xe0, 0xdb, 0xce, 0xce, 0x3c, 0x33, 0xcf, 0x3c, 0xb7,
	0x33, 0x00, 0xdb, 0xfc, 0x96, 0xd1, 0xef, 0x78, 0x3a, 0x65, 0x81, 0x08, 0x48, 0x55, 0x5b, 0xd6,
	0x01, 0x54, 0x86, 0xc3, 0x6e, 0x87, 0x34, 0x60, 0x63, 0x66, 0xbb, 0x21, 0x9a, 0xc6, 0x91, 0x71,
	0xb2, 0xd5, 0xd7, 0x86, 0xf5, 0x04, 0x6a, 0x03, 0x11, 0xde, 0xf4, 0xf1, 0x47, 0x88, 0x5c, 0x10,
	0x02, 0x15, 0xdf, 0xf6, 0xe2, 0x18, 0x75, 0xb6, 0x4e, 0x60, 0x5b, 0x87, 0xf0, 0x69, 0xe0, 0x73,
	0x24, 0x26, 0xdc, 0xf7, 0x90, 0x73, 0x7b, 0x12, 0x87, 0xc5, 0xa6, 0xf5, 0xcb, 0x80, 0xcd, 0x8f,
	0xc1, 0x0c, 0x3d, 0xf4, 0x05, 0xd9, 0x85, 0x52, 0xb7, 0x13, 0x45, 0x94, 0x74, 0x7d, 0x41, 0x85,
	0x8b, 0x66, 0x49, 0xd7, 0x57, 0x06, 0x39, 0x82, 0x9a, 0x83, 0x7c, 0xc4, 0xe8, 0x54, 0xd0, 0xc0,
	0x37, 0xcb, 0xca, 0x97, 0xbc, 0x22, 0x7b, 0x50, 0x1e, 0xf6, 0xbb, 0x66, 0x45, 0x79, 0xe4, 0x91,
	0x1c, 0xc3, 0xce, 0x18, 0x6d, 0x11, 0x32, 0x74, 0xba, 0x9e, 0xa4, 0xb1, 0xa1, 0x7c, 0xe9, 0x4b,
	0xeb, 0xb7, 0x01, 0xcd, 0x36, 0x43, 0x5b, 0x60, 0x4c, 0x29, 0x6e, 0x72, 0xce, 0xc4, 0xb8, 0x83,
	0x49, 0x69, 0x29, 0x93, 0xf2, 0x1d, 0x4c, 0x2a, 0x39, 0x4c, 0xa4, 0xa8, 0x21, 0x47, 0x16, 0xd1,
	0x54, 0x67, 0xeb, 0x29, 0xd4, 0xfb, 0x68, 0x3b, 0x59, 0x6a, 0x19, 0xd1, 0xac, 0x6f, 0xd0, 0xe8,
	0x51, 0x2e, 0xe2, 0x30, 0x9e, 0x68, 0xc1, 0xa5, 0x1e, 0x15, 0x2a, 0xb4, 0xdc, 0xd7, 0x06, 0xd9,
	0x87, 0xea, 0x98, 0xba, 0x02, 0x59, 0xc4, 0x3e, 0xb2, 0x24, 0x01, 0x1e, 0x30, 0x11, 0x31, 0x57,
	0x67, 0xeb, 0x1c, 0x9a, 0xc3, 0xa9, 0x93, 0xa3, 0xce, 0x31, 0x54, 0xa8, 0x40, 0x4f, 0x65, 0xae,
	0x9d, 0xed, 0x9d, 0x46, 0x8f, 0x6a, 0x1e, 0xa6, 0xbc, 0xd6, 0x33, 0x68, 0x76, 0xd0, 0xc5, 0x7f,
	0xe1, 0xd9, 0x0e, 0x2e, 0x60, 0x3f, 0xfb, 0x15, 0xa2, 0x77, 0xf4, 0x7f, 0x85, 0xde, 0x42, 0x23,
	0x2d, 0x54, 0x21, 0xf4, 0x39, 0x34, 0x33, 0xfa, 0x2d, 0xe0, 0x8e, 0x2d, 0x6c, 0xd3, 0x38, 0x2a,
	0xe7, 0xc3, 0xa5, 0x57, 0x92, 0xcf, 0x8a, 0x54, 0xa8, 0xfc, 0x05, 0xec, 0x67, 0x55, 0x2a, 0x82,
	0x3f, 0xfb, 0x03, 0x50, 0x1d, 0x28, 0x0f, 0xb9, 0x82, 0xba, 0xd6, 0xb1, 0x1d, 0xf8, 0x63, 0x3a,
	0x09, 0x99, 0xad, 0xde, 0x64, 0x3d, 0x46, 0x26, 0xa6, 0xb8, 0xd5, 0x48, 0x5f, 0xea, 0x92, 0xd6,
	0x3d, 0xf2, 0x1e, 0x1e, 0x4a, 0x2d, 0xd7, 0xc8, 0x70, 0x05, 0x75, 0x2d, 0xc8, 0x1a, 0x39, 0xda,
	0xd0, 0xe8, 0x20, 0x17, 0x2c, 0xf8, 0xb9, 0x46, 0x92, 0xd7, 0x00, 0x5a, 0x8e, 0x21, 0x47, 0x56,
	0x0c, 0xfa, 0x12, 0x36, 0xa5, 0x0a, 0xc5, 0x81, 0xaf, 0x60, 0x4b, 0x3e, 0x26, 0x09, 0xe4, 0x85,
	0xd9, 0x6a, 0xd9, 0x8a, 0x17, 0x7d, 0x03, 0xb5, 0x4b, 0x36, 0xba, 0xa5, 0xb3, 0x15, 0xb0, 0x5f,
	0x60, 0x37, 0x3d, 0x7b, 0xe4, 0x30, 0x8e, 0xcc, 0xdd, 0x8c, 0xad, 0xc7, 0xcb, 0xdc, 0xf3, 0x94,
	0xd7, 0xb0, 0x9d, 0x1c, 0x47, 0xf2, 0x28, 0x46, 0xe4, 0x6c, 0xb3, 0xd6, 0x41, 0xbe, 0x73, 0x9e,
	0xec, 0x13, 0xec, 0xa4, 0xa6, 0x93, 0xcc, 0x01, 0x79, 0x4b, 0xaf, 0x75, 0xb8, 0xc4, 0x9b, 0xec,
	0x37, 0x3d, 0xae, 0x8b, 0x7e, 0x73, 0x77, 0xdd, 0xa2, 0xdf, 0xfc, 0x29, 0xd7, 0x29, 0xd3, 0x13,
	0xbc, 0x48, 0x99, 0xbb, 0xff, 0x16, 0x29, 0xf3, 0x07, 0x5f, 0x4f, 0xa1, 0x96, 0xb7, 0x67, 0xfb,
	0x0e, 0xf5, 0x27, 0x9f, 0xe5, 0x6f, 0x44, 0xa1, 0xef, 0x7a, 0x01, 0x0f, 0xa4, 0xa2, 0x2b, 0xe3,
	0xdf, 0xc1, 0x9e, 0x94, 0x30, 0x81, 0xe7, 0x85, 0x17, 0x89, 0x56, 0x6c, 0x65, 0x0a, 0x97, 0x40,
	0xa2, 0x67, 0xbd, 0x72, 0x8a, 0x6b, 0x68, 0x7d, 0x40, 0xf1, 0x35, 0x70, 0x43, 0x5f, 0x20, 0xb2,
	0x5e, 0x30, 0x52, 0x7b, 0x64, 0x20, 0x18, 0xda, 0x5e, 0xa1, 0x54, 0xcf, 0x8d, 0x9b, 0xaa, 0xfa,
	0xd3, 0xf4, 0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xc2, 0x3a, 0x80, 0x44, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShrikeClient is the client API for Shrike service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShrikeClient interface {
	CreateConfiguration(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	ReadConfiguration(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	UpdateConfiguration(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	DestroyConfiguration(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	CreateUser(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	ReadUser(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	ListUsers(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	UpdateUser(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	ArchiveUser(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	CreateMovement(ctx context.Context, in *CreateMovementRequest, opts ...grpc.CallOption) (*CreateMovementResponse, error)
	ReadMovement(ctx context.Context, in *ReadMovementRequest, opts ...grpc.CallOption) (*ReadMovementResponse, error)
	ListMovements(ctx context.Context, in *ListMovementsRequest, opts ...grpc.CallOption) (*ListMovementsResponse, error)
	UpdateMovement(ctx context.Context, in *UpdateMovementRequest, opts ...grpc.CallOption) (*UpdateMovementResponse, error)
	DeleteMovement(ctx context.Context, in *DeleteMovementRequest, opts ...grpc.CallOption) (*DeleteMovementResponse, error)
	CreateLandingPage(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	ReadLandingPage(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	ListLandingPages(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	UpdateLandingPage(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	ArchiveLandingPage(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error)
	GetVolunteerLocationStream(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (Shrike_GetVolunteerLocationStreamClient, error)
}

type shrikeClient struct {
	cc *grpc.ClientConn
}

func NewShrikeClient(cc *grpc.ClientConn) ShrikeClient {
	return &shrikeClient{cc}
}

func (c *shrikeClient) CreateConfiguration(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/CreateConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ReadConfiguration(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ReadConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) UpdateConfiguration(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/UpdateConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) DestroyConfiguration(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/DestroyConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) CreateUser(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ReadUser(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ReadUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ListUsers(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) UpdateUser(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ArchiveUser(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ArchiveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) CreateMovement(ctx context.Context, in *CreateMovementRequest, opts ...grpc.CallOption) (*CreateMovementResponse, error) {
	out := new(CreateMovementResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/CreateMovement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ReadMovement(ctx context.Context, in *ReadMovementRequest, opts ...grpc.CallOption) (*ReadMovementResponse, error) {
	out := new(ReadMovementResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ReadMovement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ListMovements(ctx context.Context, in *ListMovementsRequest, opts ...grpc.CallOption) (*ListMovementsResponse, error) {
	out := new(ListMovementsResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ListMovements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) UpdateMovement(ctx context.Context, in *UpdateMovementRequest, opts ...grpc.CallOption) (*UpdateMovementResponse, error) {
	out := new(UpdateMovementResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/UpdateMovement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) DeleteMovement(ctx context.Context, in *DeleteMovementRequest, opts ...grpc.CallOption) (*DeleteMovementResponse, error) {
	out := new(DeleteMovementResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/DeleteMovement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) CreateLandingPage(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/CreateLandingPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ReadLandingPage(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ReadLandingPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ListLandingPages(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ListLandingPages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) UpdateLandingPage(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/UpdateLandingPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) ArchiveLandingPage(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (*StubResponse, error) {
	out := new(StubResponse)
	err := c.cc.Invoke(ctx, "/shrike.Shrike/ArchiveLandingPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeClient) GetVolunteerLocationStream(ctx context.Context, in *StubRequest, opts ...grpc.CallOption) (Shrike_GetVolunteerLocationStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Shrike_serviceDesc.Streams[0], "/shrike.Shrike/GetVolunteerLocationStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &shrikeGetVolunteerLocationStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Shrike_GetVolunteerLocationStreamClient interface {
	Recv() (*StubResponse, error)
	grpc.ClientStream
}

type shrikeGetVolunteerLocationStreamClient struct {
	grpc.ClientStream
}

func (x *shrikeGetVolunteerLocationStreamClient) Recv() (*StubResponse, error) {
	m := new(StubResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ShrikeServer is the server API for Shrike service.
type ShrikeServer interface {
	CreateConfiguration(context.Context, *StubRequest) (*StubResponse, error)
	ReadConfiguration(context.Context, *StubRequest) (*StubResponse, error)
	UpdateConfiguration(context.Context, *StubRequest) (*StubResponse, error)
	DestroyConfiguration(context.Context, *StubRequest) (*StubResponse, error)
	CreateUser(context.Context, *StubRequest) (*StubResponse, error)
	ReadUser(context.Context, *StubRequest) (*StubResponse, error)
	ListUsers(context.Context, *StubRequest) (*StubResponse, error)
	UpdateUser(context.Context, *StubRequest) (*StubResponse, error)
	ArchiveUser(context.Context, *StubRequest) (*StubResponse, error)
	CreateMovement(context.Context, *CreateMovementRequest) (*CreateMovementResponse, error)
	ReadMovement(context.Context, *ReadMovementRequest) (*ReadMovementResponse, error)
	ListMovements(context.Context, *ListMovementsRequest) (*ListMovementsResponse, error)
	UpdateMovement(context.Context, *UpdateMovementRequest) (*UpdateMovementResponse, error)
	DeleteMovement(context.Context, *DeleteMovementRequest) (*DeleteMovementResponse, error)
	CreateLandingPage(context.Context, *StubRequest) (*StubResponse, error)
	ReadLandingPage(context.Context, *StubRequest) (*StubResponse, error)
	ListLandingPages(context.Context, *StubRequest) (*StubResponse, error)
	UpdateLandingPage(context.Context, *StubRequest) (*StubResponse, error)
	ArchiveLandingPage(context.Context, *StubRequest) (*StubResponse, error)
	GetVolunteerLocationStream(*StubRequest, Shrike_GetVolunteerLocationStreamServer) error
}

// UnimplementedShrikeServer can be embedded to have forward compatible implementations.
type UnimplementedShrikeServer struct {
}

func (*UnimplementedShrikeServer) CreateConfiguration(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConfiguration not implemented")
}
func (*UnimplementedShrikeServer) ReadConfiguration(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadConfiguration not implemented")
}
func (*UnimplementedShrikeServer) UpdateConfiguration(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfiguration not implemented")
}
func (*UnimplementedShrikeServer) DestroyConfiguration(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyConfiguration not implemented")
}
func (*UnimplementedShrikeServer) CreateUser(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedShrikeServer) ReadUser(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUser not implemented")
}
func (*UnimplementedShrikeServer) ListUsers(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedShrikeServer) UpdateUser(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedShrikeServer) ArchiveUser(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveUser not implemented")
}
func (*UnimplementedShrikeServer) CreateMovement(ctx context.Context, req *CreateMovementRequest) (*CreateMovementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMovement not implemented")
}
func (*UnimplementedShrikeServer) ReadMovement(ctx context.Context, req *ReadMovementRequest) (*ReadMovementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMovement not implemented")
}
func (*UnimplementedShrikeServer) ListMovements(ctx context.Context, req *ListMovementsRequest) (*ListMovementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMovements not implemented")
}
func (*UnimplementedShrikeServer) UpdateMovement(ctx context.Context, req *UpdateMovementRequest) (*UpdateMovementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMovement not implemented")
}
func (*UnimplementedShrikeServer) DeleteMovement(ctx context.Context, req *DeleteMovementRequest) (*DeleteMovementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMovement not implemented")
}
func (*UnimplementedShrikeServer) CreateLandingPage(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLandingPage not implemented")
}
func (*UnimplementedShrikeServer) ReadLandingPage(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadLandingPage not implemented")
}
func (*UnimplementedShrikeServer) ListLandingPages(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLandingPages not implemented")
}
func (*UnimplementedShrikeServer) UpdateLandingPage(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLandingPage not implemented")
}
func (*UnimplementedShrikeServer) ArchiveLandingPage(ctx context.Context, req *StubRequest) (*StubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveLandingPage not implemented")
}
func (*UnimplementedShrikeServer) GetVolunteerLocationStream(req *StubRequest, srv Shrike_GetVolunteerLocationStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetVolunteerLocationStream not implemented")
}

func RegisterShrikeServer(s *grpc.Server, srv ShrikeServer) {
	s.RegisterService(&_Shrike_serviceDesc, srv)
}

func _Shrike_CreateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).CreateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/CreateConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).CreateConfiguration(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ReadConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ReadConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ReadConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ReadConfiguration(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).UpdateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/UpdateConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).UpdateConfiguration(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_DestroyConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).DestroyConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/DestroyConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).DestroyConfiguration(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).CreateUser(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ReadUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ReadUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ReadUser(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ListUsers(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).UpdateUser(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ArchiveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ArchiveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ArchiveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ArchiveUser(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_CreateMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMovementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).CreateMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/CreateMovement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).CreateMovement(ctx, req.(*CreateMovementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ReadMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMovementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ReadMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ReadMovement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ReadMovement(ctx, req.(*ReadMovementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ListMovements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMovementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ListMovements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ListMovements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ListMovements(ctx, req.(*ListMovementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_UpdateMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMovementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).UpdateMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/UpdateMovement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).UpdateMovement(ctx, req.(*UpdateMovementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_DeleteMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMovementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).DeleteMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/DeleteMovement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).DeleteMovement(ctx, req.(*DeleteMovementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_CreateLandingPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).CreateLandingPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/CreateLandingPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).CreateLandingPage(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ReadLandingPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ReadLandingPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ReadLandingPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ReadLandingPage(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ListLandingPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ListLandingPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ListLandingPages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ListLandingPages(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_UpdateLandingPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).UpdateLandingPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/UpdateLandingPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).UpdateLandingPage(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_ArchiveLandingPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServer).ArchiveLandingPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.Shrike/ArchiveLandingPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServer).ArchiveLandingPage(ctx, req.(*StubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shrike_GetVolunteerLocationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StubRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShrikeServer).GetVolunteerLocationStream(m, &shrikeGetVolunteerLocationStreamServer{stream})
}

type Shrike_GetVolunteerLocationStreamServer interface {
	Send(*StubResponse) error
	grpc.ServerStream
}

type shrikeGetVolunteerLocationStreamServer struct {
	grpc.ServerStream
}

func (x *shrikeGetVolunteerLocationStreamServer) Send(m *StubResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Shrike_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shrike.Shrike",
	HandlerType: (*ShrikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConfiguration",
			Handler:    _Shrike_CreateConfiguration_Handler,
		},
		{
			MethodName: "ReadConfiguration",
			Handler:    _Shrike_ReadConfiguration_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _Shrike_UpdateConfiguration_Handler,
		},
		{
			MethodName: "DestroyConfiguration",
			Handler:    _Shrike_DestroyConfiguration_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Shrike_CreateUser_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _Shrike_ReadUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Shrike_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Shrike_UpdateUser_Handler,
		},
		{
			MethodName: "ArchiveUser",
			Handler:    _Shrike_ArchiveUser_Handler,
		},
		{
			MethodName: "CreateMovement",
			Handler:    _Shrike_CreateMovement_Handler,
		},
		{
			MethodName: "ReadMovement",
			Handler:    _Shrike_ReadMovement_Handler,
		},
		{
			MethodName: "ListMovements",
			Handler:    _Shrike_ListMovements_Handler,
		},
		{
			MethodName: "UpdateMovement",
			Handler:    _Shrike_UpdateMovement_Handler,
		},
		{
			MethodName: "DeleteMovement",
			Handler:    _Shrike_DeleteMovement_Handler,
		},
		{
			MethodName: "CreateLandingPage",
			Handler:    _Shrike_CreateLandingPage_Handler,
		},
		{
			MethodName: "ReadLandingPage",
			Handler:    _Shrike_ReadLandingPage_Handler,
		},
		{
			MethodName: "ListLandingPages",
			Handler:    _Shrike_ListLandingPages_Handler,
		},
		{
			MethodName: "UpdateLandingPage",
			Handler:    _Shrike_UpdateLandingPage_Handler,
		},
		{
			MethodName: "ArchiveLandingPage",
			Handler:    _Shrike_ArchiveLandingPage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetVolunteerLocationStream",
			Handler:       _Shrike_GetVolunteerLocationStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "shrike.proto",
}
